name: news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  google_fonts: ^8.0.1
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/



flutter_native_splash:
  background_image: assets/splash_images/splash.png
  background_image_dark: assets/splash_images/splash_dark.png
  fullscreen: true                # default false
  android_12:
    color: "#FFFFFF"
    color_dark: "#171717"

    image: assets/splash_images/news_logo.png
    image_dark: assets/splash_images/news_dark_logo.png

    branding:      assets/splash_images/news_branding.png
    branding_dark: assets/splash_images/news_dark_branding.png
